# Use an official Python runtime as a base image
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy all files from the current directory into the container
COPY . .

# Default command to run the script
CMD ["python", "app.py"]
